CREATE TABLE IF NOT EXISTS store.Image (
	Id INT UNSIGNED auto_increment NOT NULL,
	Url VARCHAR(100) NULL,
	Base64Bytes LONG VARCHAR NULL,
	CONSTRAINT Image_pk PRIMARY KEY (Id)
)
ENGINE=InnoDB
DEFAULT CHARSET=utf8mb4
COLLATE=utf8mb4_general_ci;